version: '3.8'

services:
  assistant:
    image: localhost:5000/billy-assistant:latest
    container_name: billy_assistant
    depends_on:
      - ollama
    restart: unless-stopped
    environment:
      PROFILE_PATH: data/user_profile.json
      OLLAMA_URL: http://ollama:11434/api/generate
      QDRANT_URL: http://qdrant:6333
    ports:
      - "5001:5000"
    volumes:
      - ./data:/app/data
    networks:
      - default
      - billy-memory_default

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    command: ["serve"]
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

volumes:
  ollama-data:

networks:
  default:
  billy-memory_default:
    external: true
