version: "3.8"

networks:
  billy-network:
    external: true

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    command: ["serve"]
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - billy-network

  assistant:
    image: localhost:5000/billy-assistant:latest
    container_name: billy_assistant
    restart: unless-stopped
    depends_on:
      - ollama
    ports:
      - "5001:5000"
    volumes:
      - ./data:/app/data
    environment:
      PROFILE_PATH: data/user_profile.json
      OLLAMA_URL: "http://ollama:11434/api/generate"
      QDRANT_URL: "http://qdrant:6333"
    networks:
      - billy-network

volumes:
  ollama-data:
