version: '3.8'

services:
  assistant:
    image: localhost:5000/billy-assistant:latest
    container_name: billy_assistant
    restart: unless-stopped
    environment:
      PROFILE_PATH: data/user_profile.json
      QDRANT_URL: "http://qdrant:6333"
      OLLAMA_URL: "http://ollama:11434/api/generate"
    ports:
      - "5001:5000"
    volumes:
      - ./data:/app/data
    networks:
      - billy-network

networks:
  billy-network:
    external: true