version: "3.8"

services:
  assistant:
    image: localhost:5000/billy-assistant:latest
    container_name: billy_assistant
    restart: unless-stopped
    environment:
      PROFILE_PATH: data/user_profile.json
      OLLAMA_URL: http://ollama:11434/api/generate
      QDRANT_URL: http://ai:6333
    ports:
      - "5001:5000"
    volumes:
      - ./data:/app/data
